#!/usr/bin/env python3

# TODO
import sys
import helpers
from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile screen_name")

    # instantiate analyzer
    analyzer = Analyzer()

    # analyze word
    screen_name = sys.argv[1]
    if screen_name.startswith('@'):
        screen_name = screen_name[1:]
    tweets = helpers.get_user_timeline(screen_name, count=50)

    for tweet in tweets:
        score = analyzer.getScore([tweet])
        if score > 0.0:
            print(colored(tweet, "green"))
        elif score < 0.0:
            print(colored(tweet, "red"))
        else:
            print(colored(tweet, "yellow"))

if __name__ == "__main__":
    main()
